name: events_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  googleapis_auth: ^1.6.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  location: ^7.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/images/"
    - "assets/translations/"
